name: nginx
apiVersion: v2
version: "0.0.1"
appVersion: "0.0.1"

dependencies:
  - name: nginx
    version: 0.0.1
    repository: "https://raw.githubusercontent.com/timtsoitt/argocd-base-charts/main/releases"
