apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgDBPVenmhwjxGDDVVbMLT7cHqH6+kAWv/vLcuw8/sGY4h9E2+TTBHh9bTd0os0pCMlqTQ6PZaaal7ij0tIpQyowspCVtMXcZzny5rVcpuEGuZpIE1pTgZwItf+U+QMhbURz5lYmAXMSU4BIxGXh2rwihu9YUIbL2SuVwUd0F3lFEJjonY+O4BgYTbc/JwenrEforWHZ42r5iYX5hbmGdc55i0NZTfgQJdnCkDyIzFU/lgDO8qSUr3UMZfjCpBQ4Qusgc/8h3DuzxtW71/N8CbVm+KHc4bGoDs+Cg9TMOvPMwTVVD+5J57GpTzOViwZjgn8YZgYaFNG+9J6MasyNvyapelKM03hUMClsyCQtAa89XTLexfq5kaX0sxGSWvj7LyIwb5RgFojO7hQjDyauJzqIG1SEVlQcuODH9wX43fdu+6dBYGX6g9tSbBmqbb/A91Wg/cnN0Qexlzrmw1O5/Bph4eRUN/DDhhrjklW9l32ZlIn4SZZxmRTbe6SB/NkzJS7JGp2oUKDy5i6gTwrqtKBgtnyaWu4wSQkp/aP+MZ9Yrh/Y4VbPOPWJRCwWkD+3TaPAk5BzVlt5D9iUbAXUf8AzJmxZ4ZZ8kNdwuJLV42/6YxMievTtb4A37jIqGlJ8NAWrsFJWJUWtc14oMx4nIqWEr14rnVdVi7F0DLWDtWnVZE6GXPTDLDJT8ZmA79pT/5471RY59WHejhJRmkPNfbY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

